### ISSUE TITLE
Port ZStream combinators and constructors to the new encoding

### ISSUE THREAD

**Issue by iravid** [zio/zio#2720]
Submit PRs to `feature/zconduit`. Reply below to claim an item.

Constructors:
- [x] absolve 
- [x] access 
- [x] accessM 
- [x] accessStream 
- [x] apply(A*)
- [x] bracket 
- [x] bracketExit 
- [x] crossN 
- [x] die 
- [x] dieMessage 
- [x] effectAsync 
- [x] effectAsyncInterrupt 
- [x] effectAsyncM 
- [x] effectAsyncMaybe 
- [x] environment 
- [x] fail 
- [x] finalizer 
- [x] flatten 
- [x] flattenPar 
- [x] flattenParUnbounded 
- [x] fromChunk 
- [x] fromEffect 
- [x] fromEffectOption 
- [x] fromInputStream 
- [x] fromIterable 
- [x] fromIterator 
- [x] fromIteratorManaged 
- [x] fromJavaIterator 
- [x] fromJavaIteratorManaged 
- [x] fromQueue 
- [x] fromQueueWithShutdown 
- [x] fromTQueue 
- [x] halt 
- [x] iterate 
- [x] managed 
- [x] mergeAll 
- [x] mergeAllUnbounded 
- [x] paginate 
- [x] paginateM 
- [x] range 
- [x] repeatEffect 
- [x] repeatEffectOption 
- [x] repeatEffectWith 
- [x] succeed 
- [x] unfold 
- [x] unfoldM 
- [x] unwrap 
- [x] unwrapManaged 
- [x] zipN 
- [x] empty 
- [x] never 
- [x] unit 

Combinators:
- [x] &> 
- [x] *> 
- [x] ++ 
- [x] <& 
- [x] <&> 
- [x] <* 
- [x] <*> 
- [x] absolve 
- [x] aggregate 
- [x] aggregateAsync
- [x] aggregateAsyncWithin 
- [x] aggregateAsyncWithinEither
- [ ] ~aggregateManaged~
- [x] as 
- [x] bimap 
- [x] broadcast 
- [x] broadcastDynamic 
- [x] broadcastedQueues
- [x] broadcastedQueuesDynamic
- [x] buffer 
- [x] bufferDropping 
- [x] bufferSignal 
- [x] bufferSliding 
- [x] bufferUnbounded 
- [x] catchAll 
- [x] catchAllCause
- [x] chunkN - port as transducer
- [x] collect 
- [x] collectM 
- [x] collectWhile 
- [x] collectWhileM 
- [x] combine 
- [x] concat 
- [x] cross 
- [x] crossWith 
- [x] distributedWith 
- [x] distributedWithDynamic 
- [x] drain 
- [x] drainFork 
- [x] drop 
- [x] dropUntil 
- [x] dropWhile 
- [x] either 
- [x] ensuring 
- [x] ensuringFirst 
- [x] filter 
- [x] filterM 
- [x] filterNot 
- [x] fixed 
- [x] flatMap
- [x] flatMapPar 
- [x] flatMapParSwitch 
- [x] fold 
- [x] foldM 
- [x] foldManaged 
- [x] foldManagedM 
- [x] foldWhile 
- [x] foldWhileM 
- [x] foldWhileManaged 
- [x] foldWhileManagedM 
- [x] foreach 
- [x] foreachManaged 
- [x] foreachWhile 
- [x] foreachWhileManaged 
- [x] forever 
- [x] groupBy
- [x] groupByKey 
- [x] grouped 
- [x] groupedWithin 
- [x] haltWhen 
- [x] interleave 
- [x] interleaveWith
- [x] interruptWhen 
- [x] into 
- [x] intoManaged 
- [x] map 
- [x] mapAccum 
- [x] mapAccumM 
- [x] mapConcat 
- [x] mapConcatChunk 
- [x] mapConcatChunkM 
- [x] mapConcatM 
- [x] mapError 
- [x] mapErrorCause 
- [x] mapM 
- [x] mapMPar 
- [x] mapMParUnordered 
- [x] mapMPartitioned 
- [x] merge 
- [x] mergeEither 
- [x] mergeWith
- [x] orElse 
- [x] partition 
- [x] partitionEither 
- [x] peel 
- [x] provide 
- [x] provideM 
- [x] provideManaged 
- [x] provideSome 
- [x] provideSomeM 
- [x] provideSomeManaged 
- [x] repeat 
- [x] repeatEither 
- [x] repeatWith 
- [x] run 
- [x] runCollect 
- [x] runDrain 
- [x] runHead 
- [x] runLast 
- [x] schedule 
- [x] scheduleEither 
- [x] scheduleElements 
- [x] scheduleElementsEither 
- [x] scheduleElementsWith 
- [x] scheduleWith 
- [x] take 
- [x] takeUntil 
- [x] takeWhile 
- [x] tap 
- [x] throttleEnforce (port as transducer)
- [x] throttleEnforceM (port as transducer)
- [x] throttleShape (port as transducer)
- [x] throttleShapeM (port as transducer)
- [x] timeout 
- [x] toInputStream 
- [x] toQueue 
- [x] toQueueUnbounded 
- [x] transduce 
- [ ] ~transduceManaged~
- [x] unNone 
- [x] unTake - became unExit and unExitChunk
- [x] via 
- [x] zip 
- [x] zipLeft 
- [x] zipRight 
- [x] zipWith
- [x] zipWithIndex 
- [x] zipWithLatest

**Comment by jkobejs** [comment]
Doing fromIterable, fromIterator, fromChunk

**Comment by regiskuckaertz** [comment]
@jkobejs I did fromChunk [here](https://github.com/zio/zio/pull/2889) but happy to remove it, as I only needed it for writing a test 😅

**Comment by jkobejs** [comment]
You don't need to remove it, I'll remove it. 😄

**Comment by regiskuckaertz** [comment]
Taking flatmap.

**Comment by iravid** [comment]
Doing `fromEffect`, `bracket` and `ensuring`

**Comment by regiskuckaertz** [comment]
@iravid I took the liberty of ticking them off the list; makes it easier for people to know which ones are left for grabs.

Taking various constructors: die, fail, halt, range, succeed, empty, never, unit.

**Comment by iravid** [comment]
@regiskuckaertz Much appreciated! 🙏🏻

**Comment by iravid** [comment]
Doing take as well.

**Comment by regiskuckaertz** [comment]
Nice! I was just looking at takeWhile. It looks like for these, we will have to override the end marker to be `()`.

**Comment by iravid** [comment]
I went with `Option[B]` as that can retain maximal information

**Comment by iravid** [comment]
(although I might be proven wrong when we get to combinators that combine streams...)

**Comment by iravid** [comment]
@regiskuckaertz @vasilmkd 

This is actually pretty reminiscent of `fs2.Pull`. That one has type parameters for outputs and a result type. But only pulls with `B = Unit` can be converted back to streams.

`B` might indeed prove challenging when we start composing streams. We already glossed over it in `flatMap` - maybe we should have set the resulting `B` to `List[B1]`?

**Comment by regiskuckaertz** [comment]
Ha, yes I like both `Option` and `List`. Will use that and also update flatMap 👍

**Comment by vasilmkd** [comment]
What if these lists start to get out of hand? What about infinite lists (I know the implementation does not go through `flatMap`), but semantically, it's the same thing.

**Comment by iravid** [comment]
Yes, that's a good point. It may be infeasible to keep those `B` values around.

**Comment by iravid** [comment]
I suggest that we do not make any special effort to preserve `B` values when it is not immediately apparent how to do so. We might need some specific combinators for doing that (e.g. `flatMapAccumulate` that takes a `(B, B) => B` in addition...)

**Comment by vasilmkd** [comment]
Ok. Personally, I have no problem with that. But this has already happened before. We didn't care about errors, throwing them around at our convenience, just for the sake of fast iteration. Then the effort to correct that started, which still isn't finished, and now we are starting another rewrite. I'm not complaining, but these things, these special features, these things that are genuniely _hard_ problems (just think, `aggregateAsync`, which still isn't fixed, but I have tried, think `aggregate/transduce`, think `bufferDropping/bufferSliding`, these took me weeks of work to implement) and require a lot of effort to fix, which is even harder when trying to hit a moving target.

And to be completely honest, I don't see a compelling enough reason to go all in on a feature that makes it harder to compose the library constructs, harder to implement them, and needs to be restrained or limited to work properly.

Again, don't take my opinion too seriously. I don't have any power to influence any decision, nor should I have that power. I'm not saying this in a negative way. I apologize if I sound negative, I'm not. I only want the best for this project and for everyone involved in it.

**Comment by regiskuckaertz** [comment]
Alright, not changing flatMap then.

**Comment by iravid** [comment]
@vasilmkd Thanks for voicing that concern, it is indeed valid and your work around those combinators was essential in fleshing out how error preservation should work!

> And to be completely honest, I don't see a compelling enough reason to go all in on a feature that makes it harder to compose the library constructs, harder to implement them, and needs to be restrained or limited to work properly. I always liked ZIO because it made things easy, and was blown away when I watched the first presentation of ZStreams.

So if I follow what you're saying - you are not yet convinced by `B` on `ZStream`? I'm of the same opinion, so  I am naturally shying away from investing too much time in supporting it properly throughout the combinators.

Perhaps a saner approach would be to fix `B = Unit` in combinator return types for now?

**Comment by iravid** [comment]
To clarify, there is no hard deadline to get this branch in, as we are not guaranteeing binary compatibility for the streams module until 1.1/1.2. There's ample time, therefore, to experiment and get this right.

If you (@vasilmkd @regiskuckaertz et al) feel it's better to figure out exactly how to utilize and compose `B` values before continuing to port combinators, I'm onboard with that.

**Comment by vasilmkd** [comment]
Officially summoning @jdegoes to the discussion, just so he is aware of the `flatMap` `B`s situation.

**Comment by jkobejs** [comment]
Taking fold related combinators

**Comment by jdegoes** [comment]
I do think it's worthwhile to look at problematic cases early on. After all, we're hoping this will be the last incarnation of stream for 1.x.

On Stream `flatMap` with `B` (and `++`), to avoid losing information, you'd ideally want a semigroup on `B`. We can't do that directly, of course, but we can force `Unit` or `List` (making our own "free" semigroup), as has been suggested; the latter is inadvisable due to the possibility of infinite lists.

I'd suggest even `Unit` is too constrained for a general `flatMap`, and it's probably best to allow `B` values to vary, i.e. you can flat map to a stream with a different type for `B`, and just choosing the last type to win ("last semigroup"). That could be implemented in terms of a more general combinator that allows combining two unrelated `B` values into a single `B` value.

As for `B` itself, I am not convinced either. I just haven't had enough time to look into it. I know some Haskell libraries have streams that terminate with a value (though much more common in Pipes / Conduits style). FS2 has `Pull` which can produce a value. 

I _think_ the main use case is pulling off some data, and getting a stream as a result, e.g.:

```scala
stream.run(sink).flatMapB { case (value, stream2) => ... }
```

However, we can already do this with `Stream#peel` by switching to a different monad (`ZManaged`). I definitely don't think this feature justifies a new type parameter!

The other obvious use case is differentiating finite versus infinite streams. This would allow making errors on flatMapping (etc.) infinite streams to infinite streams, and other combinations that cannot be detected now. You can also probably feed this information forward in some operations, e.g. if you have an infinite stream, you run it using a sink, and you know you don't get back anything.

I'd rate that as a nice to have but inessential. Users can survive just fine without this information (no other library has it, anyway).

You can imagine using `B` for various things: e.g. converting a stream that can fail into one that cannot fail, but that terminates with the error. 

The only other real question I have about `B` is could it lead to a different style of using streams. e.g. if you have an operation that can shift the terminal value of a stream into a stream emitting that value (with `Unit` terminal value)`, and you have another operation that can shift emitted elements into the terminal value (e.g. running a sink). The ability to shift information between these channels in some sort of well-defined and principled way could lead to a different style of programming streams. But honestly I don't have time right now to explore it.

Overall if other folks agree, I'm fine dropping `B`, especially if it's distracting or getting in the way. I don't see anything "game changing" in the type parameter. I think aside from terminability, everything you can do with `B`, you can do with stuffing a stream inside a `Managed`.

**Comment by vasilmkd** [comment]
What if we go full conduit style? 

`ZConduit[-R, +E, -I, +O, +Z] = ZManaged[R, Nothing, I => ZIO[R, Either[E, B], O]]` with

`type ZStream[-R, +E, +O] = ZConduit[R, E, Unit, O, Unit]` and

`type ZSink[-R, +E, -I, +Z] = ZConduit[R, E, I, Unit, Z]`?

**Comment by jdegoes** [comment]
What is Z?

**Comment by vasilmkd** [comment]
> What is Z?

`B` in our previous discussion.

**Comment by vasilmkd** [comment]
First of all, sorry I couldn't write more in depth any sooner. My reasoning is the following.

Why have concepts like `degenerate` sinks (just a value) and streams with just 1 value, when we can unify them in a data structure that ends with the value (`def succeed[A](a: A): ZConduit[Any, Nothing, Unit, Nothing, A]`). If we do want a stream with 1 value, we can have the following type signature (albeit with less information), `def single[A](a: A): ZConduit[Any, Nothing, Unit, A, Unit]`, but the upside to this one is that it can be combined using the already familiar `ZStream` combinators.

`flatMap` would now be defined: `def flatMap[Z1](f: Z => ZConduit[R, E, I, O, Z1])`. For sinks, this corresponds to current day `flatMap`. For streams, this allows for the previously discussed `flatMapB` to be implemented (defaults to `Unit`, which can probably be thought of as `++`, because we are not actually acting on the end value of the Stream?).

Old stream `flatMap` can be `flatMapOutput[O1](f: O => ZConduit[R, E, Unit, O1, Unit]`?

We can "command" a stream/sink by inputting `I` elements. @iravid could this be used for example to create variable throttling configurations?

We can run a composition of `ZConduits` producing a final `ZIO[R, E, Z]`, with `Z =:= Nothing` meaning an non-terminating program.

We can compose `ZConduits` by feeding outputs of type `O` into `ZConduits` that accept `O`s as inputs (`I` type parameter).

Since we have a "single" driver (i.e. there is only one evaluable datatype, we can make leftovers first class citizens of the pipeline), there can be a `ZConduit` that represents a leftover from a consuming datatype, which can be "returned" to the upstream for later processing.

@jdegoes Does any of this hold water?

**Comment by jdegoes** [comment]
@vasilmkd I like it. You have some errors in your code snippets which confused me.

Note fiber has zip and zipWith which are really versions of `++`. I'll try to write more soon but I think you're onto something nice and clean which has the properties we want.

**Comment by vasilmkd** [comment]
I was typing these directly into github comments. I'm sure they can be corrected in a code editor. Also we probably need other type variables, for some reason `I` and `O` seem weird to type, especially when you need `I1` and `O1`, but it may just be me.

The inspiration definitely comes from the `conduit` Haskell library, but it is a ZIO native translation. 😄

**Comment by iravid** [comment]
I see several issues:
1. I am still not seeing usecases that justify adding `I` and `B` to `ZStream`, and paying the cost of bad error messages (type aliases always expand in error messages) and more sophisticated semantics. But still willing to be convinced by a good usecase! The comparison to `fs2.Pull` is a good one, but we've seen that we are able to write all combinators without `B`, whereas fs2 uses Pull's result to write recursive programs that can be converted to streams.
2. The `flatMap` target for ZStream must stay `O`. The semantics where `flatMap` targets `B` change ZStream from "an effectful iterator" to "a program that can execute effects, emit elements and read inputs". I am not sure this is a good change.
3. We don't have rebindable syntax like in Haskell, so to retain good ergonomics for both `B` and `O`, we have to introduce a newtype that changes the flatMap target. I'm not sure this is a good change either :-) (we've repeatedly emphasized ZStream's simplicity).

All in all, I am very much in favor of refactoring ZSink, but not seeing the changes to ZStream hold water yet.

**Comment by iravid** [comment]
Maybe we can ask @snoyman for common usecases for `i` and `r` on sources in `ConduitT`?

**Comment by iravid** [comment]
Thinking about this again, I'm open to `ZStream` and `ZSink` being case classes (rather than type aliases) over a more general `ZConduit` data type that can represent streams and sinks. That would eliminate most of my ergonomics concerns.

**Comment by vasilmkd** [comment]
I agree about `ZStream`, I'm already in love with its current ergonomics. `ZSink` kind of worries me these days. It seems that it has become a kitchen sink for every feature that we are hesitant to add to`ZStream`. It needs to end with a value? Check. It needs to accept input elements? Check. It needs to be queriable at any moment (essentially be a stream at the same time)? Check. It can bypass all of this and just be a value (not end with a value)? Check. For me, this is too much. I already dread sitting down and writing a few combinators, because I have to keep all of these features in my head. Not to mention that they all have non trivial semantics regarding errors and somewhat different semantics for "retryability". And frankly, I don't see anyone else giving them a serious shot. Maybe we should look to split `ZSink` into a transducer and an online aggregator as @iravid has mentioned in the past.

**Comment by vasilmkd** [comment]
Maybe these features can be distributed among the two new data types, surely they are not needed by both.

**Comment by jdegoes** [comment]
If we do the more conduit model, maybe we should use OOP here and make `ZSink` and `ZStream` extend `ZConduit`. That way "common operators" can be left in `ZConduit` and specific operators can be located in the children. Might achieve the benefits of `case class` wrappers, but also additional benefits: no need to delegate common methods to a common implementation.

**Comment by jdegoes** [comment]
While we're bikeshedding maybe we should also discuss chunkifying everything:

```scala
sealed trait ZConduit[-R, +E, -I, +O, +Z](
  run: ZManaged[R, Nothing, Chunk.NonEmpty[I] => ZIO[R, Either[E, Z], Chunk.NonEmpty[O]]])

sealed trait ZStream[-R, +E, +O] extends ZConduit[R, E, Unit, O, Unit] 

sealed trait ZSink[-R, +E, -I, +Z] extends ZConduit[R, E, I, Unit, Z]?
```

Would be awesome to get down to 1 data type in 2 flavors.

**Comment by vasilmkd** [comment]
There is one problem with this though that we are not considering, and it is the usual one: `aggregateAsync`. @iravid Would you be willing to look for an alternative solution for the whole combinator? I'm starting to suspect that using a `ZSink` might not be the best solution.

**Comment by vasilmkd** [comment]
> While we're bikeshedding maybe we should also discuss chunkifying everything:
> 
> ```scala
> sealed trait ZConduit[-R, +E, -I, +O, +Z](
>   run: ZManaged[R, Nothing, Chunk.NonEmpty[I] => ZIO[R, Either[E, Z], Chunk.NonEmpty[O]]])
> 
> sealed trait ZStream[-R, +E, +O] extends ZConduit[R, E, Unit, O, Unit] 
> 
> sealed trait ZSink[-R, +E, -I, +Z] extends ZConduit[R, E, I, Unit, Z]?
> ```
> 
> Would be awesome to get down to 1 data type in 2 flavors.

Returning a non empty chunk of units seems a bit strange to me.

**Comment by vasilmkd** [comment]
> If we do the more conduit model, maybe we should use OOP here and make `ZSink` and `ZStream` extend `ZConduit`. That way "common operators" can be left in `ZConduit` and specific operators can be located in the children. Might achieve the benefits of `case class` wrappers, but also additional benefits: no need to delegate common methods to a common implementation.

If you think about it more carefully, the "common" combinators would be the combinators that are more traditional to `ZSink`, and would utilize features that are just not needed in `ZStream` like pushing, producing a final value and returning remainders.

What if we instead define a `ZPipeline[-R, +E, -I, +O, +Z] =:= ZConduit[R, E, I, O, Z]` which would contain the logic for interaction between the sinks and the streams of a pipeline (be the ultimate driver), and `ZStream` and `ZSink` don't necessarily need to extend from it, if it doesn't make sense.

That way `ZStream` and `ZSink` can continue to be their own separate entities with their own separate features.

**Comment by jdegoes** [comment]
@vasilmkd I did briefly consider online aggregation:

```scala
final case class ZAggregator[-R, +E, -I, S](initial: S, process: ZConduit[R, E, (S, I), S, S])
```

**Comment by iravid** [comment]
@jdegoes 

> If we do the more conduit model, maybe we should use OOP here and make ZSink and ZStream extend ZConduit. That way "common operators" can be left in ZConduit and specific operators can be located in the children. Might achieve the benefits of case class wrappers, but also additional benefits: no need to delegate common methods to a common implementation.

That'd be nice. Which operators would be common to the two? And say we've been upcasted to a conduit - how do we get back to a more specific type?

> While we're bikeshedding maybe we should also discuss chunkifying everything:
> 
> ```scala
> sealed trait ZConduit[-R, +E, -I, +O, +Z](
>   run: ZManaged[R, Nothing, Chunk.NonEmpty[I] => ZIO[R, Either[E, Z], Chunk.NonEmpty[O]]])
> 
> sealed trait ZStream[-R, +E, +O] extends ZConduit[R, E, Unit, O, Unit] 
> 
> sealed trait ZSink[-R, +E, -I, +Z] extends ZConduit[R, E, I, Unit, Z]?
> ```
> 
> Would be awesome to get down to 1 data type in 2 flavors.

One of the biggest downsides of implicit chunking is how easy it is to lose the chunking (by doing e.g. `stream.flatMap(ZStream.succeed(_))`. I find the explicit chunking a nice benefit of the current implementation.

@vasilmkd 

> There is one problem with this though that we are not considering, and it is the usual one: aggregateAsync. @iravid Would you be willing to look for an alternative approach to the whole combinator? I'm starting to suspect that using a ZSink might not be the best solution.

What is the problem? A composable aggregator sink turned out to be a very fitting abstraction there in many usecases.

**Comment by vasilmkd** [comment]
Agreed on the chunking.

@iravid `ZSink` as defined in terms of `ZConduit` doesn't directly support querying the state. It needs a wrapper like `ZAggregator` sketched above.

**Comment by jdegoes** [comment]
@vasilmkd 

@iravid and I discussed transducer as another type of conduit:

```scala
sealed trait ZConduit[-R, +E, -I, +O, +Z](
  run: ZManaged[R, Nothing, I => ZIO[R, Either[E, Z], O]])

sealed trait ZStream[-R, +E, +O] extends ZConduit[R, E, Unit, O, Unit] 

sealed trait ZSink[-R, +E, -I, +Z] extends ZConduit[R, E, I, Unit, Z]?

sealed trait ZTransducer[-R, +E, -I, +O] extends ZConduit[R, E, I, O, Unit]?
```

Common operations (from `Profunctor`, `Arrow`, and error handling / scheduling stuff) would go on the supertype `ZConduit` (and possibly be overridden in subtypes to the most specific type possible, e.g. composing a stream with a transducer should yield a stream, rather than a conduit), while anything `Applicative` and lower would go on the subtypes or as syntax on specific subtypes, depending on its requirement. That way there are no confusing type errors and everything is properly specialized to the use case.

Then we would eventually introduce the following specializations:

 - A specialized version of `ZStream` that is backed by an `InputStream`
 - A specialized version of `ZSink` that is backed by an `OutputStream`
 - A specialized version of `ZTransducer` that is backed by a mutable (but copy-able) state machine (for reframing, decoding, etc.)

The above are necessary for high-performance.

These would be further subtypes of `ZStream` / `ZSink` / `ZTransducer`, respectively. We would possibly introduce a couple more that exist purely for interesting fusion cases.

On chunk-ification, I'm torn: while explicit chunking makes you more aware of the loss of chunkiness, it also makes it less likely for people to opt-in to chunking. Possibly, if we were willing to add a phantom type parameter, we could track chunks in the type system, and warn if the user tries to do something that transitions `Chunked` to `NonChunked`.

**Comment by vasilmkd** [comment]
I think we will still need a `ZAggregator` as I currently don't see a way for `ZTransducer` to output an `O` without providing an `I` (needed for `aggregateAsync`).

@jdegoes Are you saying we should press forward with this design? 😱

**Comment by iravid** [comment]
Possibly we could have an `exposeState` combinator that results in a `Ref` (or similar construct) that you could query for the current state?

**Comment by iravid** [comment]
> On chunk-ification, I'm torn: while explicit chunking makes you more aware of the loss of chunkiness, it also makes it less likely for people to opt-in to chunking. Possibly, if we were willing to add a phantom type parameter, we could track chunks in the type system, and warn if the user tries to do something that transitions Chunked to NonChunked.

Yes, the biggest issue today with chunking is that not all combinators are ported, so staying chunked is not as attractive. Let's go ahead with doing implicit chunking. I found myself flattening out chunks a bunch of times to improve ergonomics so this is telling.

**Comment by vasilmkd** [comment]
> Possibly we could have an `exposeState` combinator that results in a `Ref` (or similar construct) that you could query for the current state?

This is what I meant by an alternative approach to `aggregateAsync`. :+1:

@iravid Missing combinators seems more like a sign of a young library. It is our own fault as implementors too, we seem to overlook `ZStreamChunk` when adding new features.

I'm hesitant to go for implicit chunking at the moment. Would you allow some more time to think about it?

**Comment by iravid** [comment]
> This is what I meant by an alternative approach to aggregateAsync. 👍
Ah, sure. `aggregateAsync`'s API doesn't have to change; it can do that adaptation internally.

> Missing combinators seems more like a sign of a young library. It is our own fault as implementors too, we seem to overlook ZStreamChunk when adding new features.
>
> I'm hesitant to go for implicit chunking at the moment. Would you allow some more time to think about it?

Sure.

Some more of my thoughts on this:
- The only benefit to explicit chunking is not losing the chunking accidentally. Phantom types are an interesting approach but we are already on 5 type parameters :-P Other cons to explicit chunking is the need to write combinators that handle both cases. That's pretty hard! Think about writing two versions of `aggregateAsyncWithin` that are pretty different. Not fun.
- Implicit chunking has the benefit of doing the "right thing" by default (preserving chunks), but being a bit harder to debug. I'm not sure that harder to debug holds in practice.

**Comment by vasilmkd** [comment]
Ok, I see your point. Just out of curiosity, would Dotty's match types help out in this situation (and the typeclass workaround that you sketched out for me). Not saying we should pursue it, just interested.

**Comment by vasilmkd** [comment]
Having an empty `Chunk[I]` fed to the push method on `ZSink` can be used as a signal to extract the current state. Maybe. We might have a problem with `Chunk[Unit]` being fed to a `ZStream` though. Not sure how `I =:= Nothing` would work in this case?

**Comment by jdegoes** [comment]
Right, I feel like, with manual chunking:

 - ❌ few people will use it (only super knowledgeable experts for high-perf scenarios)
 - ❌ it's twice the code to maintain
 - ✅ it's clear when you lose chunking

With automatic chunking:

 - ✅ everyone will use it
 - ✅ it's half the code to maintain
 - ❌ it's unclear when you lose chunking (but experts can figure it out)

Thus it seems like automatic chunking is preferable. 

@vasilmkd We need a `NonEmpty` subtype of Chunk, e.g. `Chunk.NonEmpty`. Well, we don't need it, but it would be quite useful. I don't think `Chunk[Unit]` being fed into `ZStream` is a problem, since it's gonna ignore the input and in practice, when running, we'll be internally just feeding it `Chunk.unit` a single time and pulling the results repeatedly.

`I` can never be `Nothing` (with or without chunk), but it can be `Any` for a conduit that doesn't care about input.

**Comment by jdegoes** [comment]
> Having an empty Chunk[I] fed to the push method on ZSink can be used as a signal to extract the current state.

I think that's interesting. Certainly, if we don't have `Chunk.NonEmpty` requirement on input, then we have the type-level guarantee that you can always extract "state" for what would be a `ZTransducer`. Which is enough to satisfy online aggregation requirement.

The main tradeoff is that allowing empty chunks on either side just makes more work for common cases, but we can abstract over that, of course.

**Comment by jdegoes** [comment]
So we are at some variation of:

```scala
sealed trait ZConduit[-R, +E, -I, +O, +Z] {
  def run: ZManaged[R, Nothing, Chunk[I] => ZIO[R, Either[E, Z], Chunk[O]]]
}

sealed trait ZStream[-R, +E, +O] extends ZConduit[R, E, Unit, O, Unit] 

sealed trait ZSink[-R, +E, -I, +Z] extends ZConduit[R, E, I, Unit, Z]

sealed trait ZTransducer[-R, +E, -I, +O] extends ZConduit[R, E, I, O, Unit]
```

where `ZTransducer` is also used for online aggregation, where `O` is the state of the aggregator (which means we should have easy / friendly applicative composition over these things).

**Comment by vasilmkd** [comment]
Exposing subtypes of `Chunks` is not something that we have done up to now and might interfere with the planned improvements (hopefully). It would be harder to maintain source and binary compatibility in case of changes.

**Comment by iravid** [comment]
Actually going back on `ZTransducer` - why do we need both `ZSink` and `ZTransducer`? It appears that `ZTransducer` can express the same things that `ZSink` can.

**Comment by vasilmkd** [comment]
Yeah, with an empty `Chunk` as input, it serves mostly as a type alias to `ZSink` it seems.

**Comment by iravid** [comment]
Right. We can safely start off with `ZSink` only and tackle online aggregation first to see how feasible it is to handle.

**Comment by jdegoes** [comment]
Sinks produce a value when they are done. Transducers produce (potentially) a value at every step. So they have different forms

**Comment by iravid** [comment]
Aren't we saying that a sink is a transducer that outputs Unit values?

**Comment by jdegoes** [comment]
Not quite:

 - transducers never finish (Z should be Nothing, in fact)
 - sinks finish with a value
 - transducers compose applicatively on output
 - sinks compose applicatively/monadically on terminal value

**Comment by iravid** [comment]
Ok! Let’s see where this takes us

**Comment by iravid** [comment]
@vasilmkd would you have the cycles to refactor the staging branch?

**Comment by vasilmkd** [comment]
It will be my absolute honor. I always find cycles for ZIO.

**Comment by jdegoes** [comment]
@vasilmkd Careful there, you'll end up working for Ziverge 😂

**Comment by vasilmkd** [comment]
Are 100 pull requests to ZIO a good enough portfolio? Fifth contributor by lines added? Asking for a friend. @jdegoes

**Comment by iravid** [comment]
Updated the description. New staging branch is `feature/zconduit`.

**Comment by iravid** [comment]
I am also still unclear on which current ZSinks stays ZSinks and which ZSinks become ZTransducers. I guess this will clarify as we go, but @jdegoes @vasilmkd please share any intuitions/examples you might have.

**Comment by jdegoes** [comment]
Any reframing ones will become transducers. Actually, I think we can have a combinator, `ZSink#toTransducer` that turns a sink into a transducer, by repeating it. Then `ZStream#transduce(sink)` will simply be implemented as `self >>> sink.toTransducer`.

**Comment by vasilmkd** [comment]
@jdegoes I'm not sure that `ZStream#transduce` can work that way. There is no way to know when to stop feeding a transducer, because each `O` it produces is a valid output that needs to continue downstream.

**Comment by jdegoes** [comment]
@vasilmkd The new transducers do not stop. They are pure transducers and transform many-to-many, e.g. reframing, json decoding, unzipping, etc.

>>> is arrow composition and does not involve resetting left or right.

**Comment by vasilmkd** [comment]
So each feed to the `Transducer` is outputted downstream?

Are they allowed to keep state? Because if they don't it means that we can remove the `ZManaged` layer from the implementation, and I'm not sure if that means that a `ZSink` can be converted to a transducer, because it does keep state.

Sorry if I'm being confused for no reason.

**Comment by iravid** [comment]
They have to be stateful, yes. E.g. if you're decoding json lines and are currently searching for a newline.

**Comment by jdegoes** [comment]
> So each feed to the Transducer is outputted downstream?

Yes, unless we define a rule saying an empty chunk does not need to be passed down (as an optimization). But otherwise, yes, always.

> Are they allowed to keep state?

They are certainly stateful (sinks and transducers), and transducers and sinks cannot be unified further (beyond conduit) because sinks end with a value, and transducers never end.

**Comment by regiskuckaertz** [comment]
With the zconduit encoding I tried to write `collectAll`:

```scala
sealed abstract class ZSink[-R, +E, -I, +Z](
  override val run: ZManaged[R, Nothing, Chunk[I] => ZIO[R, Either[E, Z], Chunk[Unit]]]
) extends ZConduit[R, E, I, Unit, Z](run)

object ZSink {
  def apply[R, E, I, Z](run: ZManaged[R, Nothing, Chunk[I] => ZIO[R, Either[E, Z], Chunk[Unit]]]): ZSink[R, E, I, Z] =
    new ZSink(run) {}

  def collectAll[A]: ZSink[Any, Nothing, A, List[A]] =
    ZSink {
      Managed.fromEffect {
        Ref.make[Chunk[A]](Chunk.empty).map { as =>
          is => as.updateAndGet(_ ++ is) >>= (as => IO.fail(Right(as.toList)))
        }
      }
    }
}
```

is that right? It feels weird to fail all the time. Or perhaps sending an empty chunk should be the signal to fail and convert to a list? Still feels a bit artificial.

**Comment by vasilmkd** [comment]
I'm still unsure how to properly handle leftovers. I feel like I've failed to do that before proposing this encoding.

**Comment by vasilmkd** [comment]
@regiskuckaertz I would say sending an empty chunk should be the signal to stop accumulating.

**Comment by regiskuckaertz** [comment]
Yeah. Or perhaps it is a transducer, since it can produce a list at any point in time. But the fact it is used to collect _all_ makes me think it is a sink. 🙃

**Comment by jdegoes** [comment]
@vasilmkd Don't worry about leftovers too much, they can be encoded as a special type of sink that emits:

```scala
final case class Remainder[+A, +B](value: A, remainder: B)
```

This is really only necessary for applicative and monad operators on sinks.

@regiskuckaertz 

If you have to fail in every step, it's a good sign it's a transducer and not a sink. Failure should only be used when something is "done".

So we have two choices:

 - Use an empty chunk to force a sink to produce its done value. We were planning on using empty chunks to extract the "current" value from a transducer. There's a potential conflict here with the `bind` operator of a sink: it will switch over when one sink is done. But we could potentially address that with a law saying that empty chunk is always purely a signal and that bind may not transition on empty chunk input. We'd just have to make that rigorous because reasoning about sink termination is very important.
 - Use a transducer for `collectAll` and similar. This doesn't really solve the problem so much as defer it, since ultimately, you want a way to pipe a transducer into a sink to get some terminal value, but you can only do that if the sink knows when the stream is done or at least can pretend the stream is done on some type of signal input.

**Comment by iravid** [comment]
Now that we’re doing implicit chunking and always using chunks on inputs, we could wrap that in Option to signal stream end without losing too much performance.

This way we don’t have to overload the meaning of empty chunks and not worry about always sending non-empty chunks throughout the stream.

**Comment by regiskuckaertz** [comment]
Ah yeah I think `collectAll` is a sink after all, and perhaps a transducer equivalent could be called `ZTransducer.scan` or similar. So something like this instead, which could easily be adapted to receive an `Option[Chunk[I]]`:

```scala
object ZSink {
  object Push {
    def emit[A](a: A): IO[Either[Nothing, A], Nothing] = IO.fail(Right(a))
    val next: UIO[Chunk[Unit]] = UIO(Chunk.unit)
  }

  def collectAll[A]: ZSink[Any, Nothing, A, List[A]] =
    ZSink {
      Managed.fromEffect {
        Ref.make[Either[List[A], Chunk[A]]](Right(Chunk.empty)).map { as =>
          is => as.modify {
            case l @ Left(as) => Push.emit(as) -> l
            case Right(as)    => is match {
              case Chunk.Empty => val asl = as.toList; Push.emit(asl) -> Left(asl)
              case _           => Push.next -> Right(as ++ is)
            }
          }.flatten
        }
      }
    }
}
```

So I was writing `ZStream#run` at the same time and I think the only thing that is weird to play with is the implicit contract of "sending an empty chunk/none will terminate the sink which will manifest itself as a failure".

```scala
trait ZStream[R, E, A] {
  def run[B](sink: Sink[R, E, A, B]): ZIO[R, E, B] = {
    (self.process zip sink.run).use { case (pull, push) =>
      def go = pull.foldCauseM(
        c => Cause.sequenceEither.fold(_ => push(None) /* (1) */, ZIO.halt(_)),
        a => push(Some(Chunk.single(a))) /* (2) */ *> go
      )
      go
    }
  }
}
```

In (1), we assume that the result will be a failure, so it will be a matter of turning a `ZIO[R, Either[E, B], Chunk[Unit]]` into a `ZIO[R, E, B]`, but we still must account for success, even though by contract it is impossible.

In (2), we assume that the result will be a success, turning a `ZIO[R, Either[E, B], Chunk[Unit]]` into a `ZIO[R, E, Chunk[Unit]]`, and the same problem happens here.

Don't you think this is an avenue for bugs? It would be great if, when we push a value, the type system guarantees the sink will not end, and conversely when we signal the end, the type system guarantees the sink is ended.

**Comment by regiskuckaertz** [comment]
Just for reference: https://github.com/zio/zio/compare/feature/zconduit...regiskuckaertz:rk-constructors-zconduit#diff-abdb82129eb2f8ac241976bbfe32e72fR136-R153

**Comment by jdegoes** [comment]
@iravid 

> Now that we’re doing implicit chunking and always using chunks on inputs, we could wrap that in Option to signal stream end without losing too much performance.

That's probably preferable. 

A natural question is, do we use:

 - `Option[Chunk[I]]`
 - `Either[Option[IE], Chunk[I]]`

That is, do downstream conduits benefit from knowing whether upstream conduits terminated with error, or successfully? In most cases, I think not, transducers cannot do anything with a failure, other than emit the current state, which they must always do; and sinks will probably always, when signaled an end, terminate with their final value.

@regiskuckaertz 

So just to be clear I understand: you would like for us to encode, at the type-level, that when we send an end signal to a sink, it must terminate?

I think that would be a desirable property to prevent some protocol bugs.

Perhaps something like this:

```scala
sealed trait Signal[+I] {
  type Emit[O]
}
object Signal {
  case object End extends Signal[Nothing] {
    type Emit[O] = Nothing
  }
  final case class Continue[I](input: Chunk[I]) extends Signal[I] {
    type Emit[O] = Chunk[O]
  }
}

trait SignalFunction[-R, +E, -I, +O, +Z] {
  def apply[S <: Signal[I]](signal: S): ZIO[R, Either[E, Z], signal.Emit[O]]
}
```

where `ZConduit` now produces a `SignalFunction` wrapped in a `ZManaged`.

**Comment by regiskuckaertz** [comment]
@jdegoes yes precisely. I had the phantom type but was missing `Emit`. Thank you 🙏 will try that encoding.

**Comment by jdegoes** [comment]
@regiskuckaertz This change would mean transducers must fail on stream end, since they cannot output a terminal value of Nothing.

I'm trying to decide if that's good or bad...

**Comment by regiskuckaertz** [comment]
How about moving the final value into `Emit` too? Then a transducer would also have a way out?

```scala
sealed trait Signal[+I] {
  type Emit[+O, +Z]
}
object Signal {
  case object End extends Signal[Nothing] {
    type Emit[+O, +Z] = Z
  }
  final case class Continue[I](input: Chunk[I]) extends Signal[I] {
    type Emit[+O, +Z] = Chunk[O]
  }
}

trait SignalFunction[-R, +E, -I, +O, +Z] {
  def apply[S <: Signal[I]](signal: S): ZIO[R, E, signal.Emit[Z, O]]
}
```

**Comment by regiskuckaertz** [comment]
ha, no it doesn't help transducers.

**Comment by jdegoes** [comment]
@regiskuckaertz 

The problem is that transducers have `Z =:= Nothing`, so they can't ever emit a terminal (`Z`) value; and, moreover, we don't want to allow sinks to emit the `Z` value on the output channel, as that would complicate combinators (they should be forced to output `Z` on the `Either[E, Z]` termination channel).

If end-of-stream were all we had to worry about, then it's not an issue for transducers to error, say with `Unit`, if they are fed end-of-stream. Because then in `source >>> transducer >>> sink`, the `>>>` operator, discovering the transducer fails with `Unit`, can then propagate end-of-stream to `sink`, to obtain the error or value of the sink.

However, we have to deal with transducers that can fail, too. So in `l >>> r`, the `>>>` operator, if it detects that `l` fails for some reason, then that reason either has to make it to the output type of `l >>> r` (which implies `Unit` will cause pains, because it won't easily compose with the error type of `r`); **or**, the `>>>` operator has to feed the error (`Unit`) of `l` into `r` to get out either a success or the composed error type.

I think I like the latter approach more.

This would lead to a state machine something like this:

```scala

sealed trait ZConduit[-R, +E, -I, +O, +Z] {
  def run: ZManaged[R, Nothing, SignalFunction[R, E, I, O, Z]]
}

sealed trait ZStream[-R, +E, +O] extends ZConduit[R, E, Unit, O, Unit] 

sealed trait ZSink[-R, +E, -I, +Z] extends ZConduit[R, E, I, Unit, Z]

sealed trait ZTransducer[-R, +E, -I, +O] extends ZConduit[R, E, I, O, Nothing]

sealed trait Signal[+I] {
  type Emit[+O]
  type Terminate[+E, +Z]
}
object Signal {
  case object End extends Signal[Nothing] {
    type Emit[+O]    = Nothing
    type Terminate[+E, +Z] = Either[Option[E], Z]
  }
  final case class Cont[I](input: Chunk[I]) extends Signal[I] {
    type Emit[+O]    = Chunk[O]
    type Terminate[+E, +Z] = Either[E, Z]
  }
}
trait SignalFunction[-R, +E, -I, +O, +Z] {
  def apply[S <: Signal[I]](signal: S): ZIO[R, signal.Terminate[E, Z], signal.Emit[O]]
}
```

This would allow error type `E` (and, of course, `Z`) to be `Nothing` for most transducers, which composes nicely in `>>>`.

**Comment by iravid** [comment]
```
  def apply[S <: Signal[I]](signal: S): ZIO[R, signal.Terminate[E, Z], signal.Emit[O]]
```

This is really clever. I hope we don't run into GADT shenanigans in the implementation of the `SignalFunction`, where pattern-matching on `signal: S` doesn't expose the type member properly and requires casting the return value from the function.

**Comment by regiskuckaertz** [comment]
Tried yesterday and I’m afraid we do 😭 but of I’m not mistaken we can add methods on signal to witness the coercion. Will try when back from the gym.

**Comment by regiskuckaertz** [comment]
Right so nope, there is no method when you don't know the input type. So it's casting, which is not looking great:

```scala
  def collectAll[A]: ZSink[Any, Nothing, A, List[A]] =
    ZSink {
      Managed.fromEffect {
        Ref.make[Chunk[A]](Chunk.empty).map { as =>
          new SignalFunction[Any, Nothing, A, Unit, List[A]] {
            def apply[S <: Signal[A]](signal: S): ZIO[Any, signal.Terminate[Nothing, List[A]], signal.Emit[Unit]] =
              signal match {
                case Signal.End => 
                  as.get
                    .map(_.toList)
                    .flip
                    .asInstanceOf[ZIO[Any, signal.Terminate[Nothing, List[A]], signal.Emit[Unit]]]
                case Signal.Continue(as1) =>
                  as.update(_ ++ as1) *> 
                    Push.next.asInstanceOf[ZIO[Any, signal.Terminate[Nothing, List[A]], signal.Emit[Unit]]]
              }
          }
        }
      }
    }
```

 So perhaps not worth it after all.

**Comment by iravid** [comment]
@regiskuckaertz https://japgolly.blogspot.com/2017/06/dependently-typed-functions.html @japgolly wrote up some workarounds for that issue a while back.

It forces you to `fold` the `signal`, which maybe isn't too bad?

**Comment by regiskuckaertz** [comment]
Lol I literally thought about a fold in my sleep, I’ll play with that idea 👍

**Comment by vasilmkd** [comment]
I'm sorry if this is a stupid question, but have we not arrived back to the managed `Pull[R, E, A] => ZIO[R, Either[E, B], Unit]` encoding for `ZSink` (accepting a reified result of the stream pull, which to me looks like a repackaging of the pull itself)? Again, sorry if I'm completely off base here.

**Comment by jdegoes** [comment]
@vasilmkd Not at all! In that encoding, the sink itself is responsible for pulling elements from the stream. The conduit encoding has not changed since the above versions (`SignalFunction`, if we use it, is only about guaranteeing that you can force a value from a sink when the stream ends).

**Comment by vasilmkd** [comment]
Can we maybe go for a simpler representation, for example extending `Take` with a fourth case, `case object Query extends Take[Nothing]`? 
cc @iravid

**Comment by jdegoes** [comment]
I think I prefer just `Option[Chunk[I]]` because there are only 2 cases: it's done or there's more.

I will write this up later. I think I found a simple way to solve the transducer issue.

**Comment by japgolly** [comment]
> @regiskuckaertz https://japgolly.blogspot.com/2017/06/dependently-typed-functions.html @japgolly wrote up some workarounds for that issue a while back.

Hehe, nice flashback seeing that article. It'll be better in Scala 3 in that you'll literally be able to do stuff like `type X = (f: F) => f.Y` but unfortunately writing libraries rather than apps means you're always years behind.

If you're (wanting to) work with existential types, especially in a Scala-friendly way, this talk is probably going to be good value too: https://www.youtube.com/watch?v=9RvWDDZK3D8

**Comment by regiskuckaertz** [comment]
Still a lot of boilerplate but it works:

```scala
abstract class SignalFunction[-R, +E, -I, +O, +Z] {
  def apply[S <: Signal[I]](signal: S): ZIO[R, signal.Terminate[E, Z], signal.Emit[O]] =
    signal.fold(this)

  def onEnd: ZIO[R, Signal.End.Terminate[E, Z], Signal.End.Emit[O]]
  def onContinue[I1 <: I](cont: Signal.Continue[I1]): ZIO[R, cont.Terminate[E, Z], cont.Emit[O]]
}

object Sink {
  def collectAll[A]: ZSink[Any, Nothing, A, List[A]] =
    ZSink {
      Managed.fromEffect {
        Ref.make[Chunk[A]](Chunk.empty).map { as =>
          new SignalFunction[Any, Nothing, A, Unit, List[A]] {
            val onEnd: ZIO[Any, Either[Option[Nothing], List[A]], Nothing] = as.get.map(_.toList).map(Right(_)).flip
            def onContinue[A1 <: A](cont: Signal.Continue[A1]): ZIO[Any, Either[Nothing, List[A]], Chunk[Unit]] =
              as.update(_ ++ cont.input) *> Push.next
          }
        }
      }
    }
}
```

Without all these antics we'd have something like:

```scala
  ZSink {
    Managed.fromEffect {
      Ref.make[Chunk[A]](Chunk.empty).map { as =>
        {
           case Chunk.empty => as.get.map(as => Right(as.asList)).flip
           case as0 => as.update(_ ++ as0) *> Push.next
        }
      }
    }
  }
```
