### ISSUE TITLE
Defect in zio.Has: Set(SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]) statically known to be contained within the environment are missing

### ISSUE THREAD

**Issue by dpennell** [zio/zio#4809]
This is similar to https://github.com/zio/zio/issues/4340.

sttp zio - v3.1.7
zio -        v1.0.4-2 and 1.0.5

I haven't been able to minimize this yet and won't be able to for a couple of days, but thought I'd see if anybody has any ideas.

TIA,
-david

**Comment by dpennell** [comment]
@neko-kai tagging you due to similarity with #3558

**Comment by virusdave** [comment]
I had something similar, and crafted a local ZLayer that looked like:
```
/** Local impl because of seeming macro bug in LightTypeTag macro impl */
object LocalSlackClient {
  lazy val live: ZLayer[Has[SttpClient.Service], Nothing, SlackClient] = ???  // locally duplicated code here
```

and this got me past the immediate failure.  I also haven't had time to minimize yet.

**Comment by dpennell** [comment]
Thanks for the workaround.  I wasn't able to make that work in the time I had available.  I'll work on minimization this weekend.

**Comment by neko-kai** [comment]
@dpennell Can't reproduce locally and with scastie (https://scastie.scala-lang.org/rqC3PUk9QSeg45Zxae6GHA). For these issues reproduction more or less equals solution (since they're deterministic) but I can't guess at the problem without a reproduction either...

**Comment by hamsterready** [comment]
Try code from https://sttp.softwaremill.com/en/latest/examples.html#get-and-parse-json-using-the-zio-async-http-client-backend-and-circe

```
package sttp.client3.examples

import sttp.client3._
import sttp.client3.circe._
import sttp.client3.asynchttpclient.zio._
import io.circe.generic.auto._
import zio._
import zio.console.Console

object GetAndParseJsonZioCirce extends App {

  override def run(args: List[String]): ZIO[ZEnv, Nothing, ExitCode] = {

    case class HttpBinResponse(origin: String, headers: Map[String, String])

    val request = basicRequest
      .get(uri"https://httpbin.org/get")
      .response(asJson[HttpBinResponse])

    // create a description of a program, which requires two dependencies in the environment:
    // the SttpClient, and the Console
    val sendAndPrint: ZIO[Console with SttpClient, Throwable, Unit] = for {
      response <- send(request)
      _ <- console.putStrLn(s"Got response code: ${response.code}")
      _ <- console.putStrLn(response.body.toString)
    } yield ()

    // provide an implementation for the SttpClient dependency; other dependencies are
    // provided by Zio
    sendAndPrint
      .provideCustomLayer(AsyncHttpClientZioBackend.layer())
      .exitCode
  }
}

```

scala 2.12.10 + zio 1.0.5 + sttp 3.2.0

```
java.lang.Error: Defect in zio.Has: Set(SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]) statically known to be contained within the environment are missing
	at zio.Has$HasSyntax$.prune$extension(Has.scala:198)
	at zio.Has$HasSyntax$.union$extension(Has.scala:210)
	at zio.Has$Union$$anon$2.union(Has.scala:92)
	at zio.Has$Union$$anon$2.union(Has.scala:90)
	at zio.ZLayer.$anonfun$$plus$plus$1(ZLayer.scala:54)
	at zio.ZManaged.$anonfun$zipWithPar$6(ZManaged.scala:1156)
	at zio.ZIO.$anonfun$zipWithPar$2(ZIO.scala:2198)
	at zio.ZIO$MapFn.apply(ZIO.scala:4224)
	at zio.ZIO$MapFn.apply(ZIO.scala:4222)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:913)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:775)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by hamsterready** [comment]
Scala `2.12.10` - fails, `2.12.13` and `2.13.5` - works fine.

**Comment by dpennell** [comment]
Thanks! I'm on Scala `2.12.8` - I'll try bumping to `2.12.13` - won't be until this weekend.

**Comment by neko-kai** [comment]
@hamsterready Reproduced on 2.12.10, investigating...

**Comment by AntonShtyrkin** [comment]
@neko-kai looks like i've got a similar problem with that.

Reproduced with this example:
```
import zio._

import shapeless.tag
import shapeless.tag.@@

sealed trait Marker

trait Traitable[F[_]] {
  def get(): Unit
}

object Traitable {
  val live =
    (for {
      s <- ZIO.service[Traitable[Option] @@ Marker]
    } yield s).toLayer
}

val t = new Traitable[Option] {
  def get() = println("Oleg")
}

val v = ZLayer.succeed(tag[Marker](t)) >>> Traitable.live

Runtime.default.unsafeRun(v.build.use(p => ZIO.succeed(p.get[Traitable[Option] @@ Marker].get())))
```

scala 2.13.5 + zio 1.0.6 + shapeless 2.3.3

```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Could not find {$read::$iw::Traitable[=λ %1:0 → Option[+1:0]] & tag::Tagged[=$read::$iw::Marker]} inside Map({$read::$iw::Traitable[=λ %1:0 → Option[+1:0]] & tag::Tagged[=$read::$iw::Marker]} -> $line6.$read$$iw$$anon$1@6a60851f)
	at zio.Has$HasSyntax$.$anonfun$get$extension$2(Has.scala:181)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:228)
	at zio.Has$HasSyntax$.$anonfun$get$extension$1(Has.scala:181)
	at scala.collection.immutable.Map$Map1.getOrElse(Map.scala:250)
	at zio.Has$HasSyntax$.get$extension(Has.scala:179)
	at zio.ZIO$.$anonfun$service$1(ZIO.scala:3848)
	at zio.ZIO$AccessPartiallyApplied$.$anonfun$apply$9(ZIO.scala:4238)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:549)
	at zio.Runtime.unsafeRunWith(Runtime.scala:207)
	at zio.Runtime.unsafeRunSync(Runtime.scala:81)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:78)
	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:273)
	at zio.Runtime.unsafeRun(Runtime.scala:58)
	at zio.Runtime.unsafeRun$(Runtime.scala:57)
	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:273)
	at $line8.$read$$iw.<init>(<console>:1)
	at $line8.$read.<init>(<console>:13)
	at $line8.$read$.<clinit>(<console>)
	at $line8.$eval$.$print$lzycompute(<synthetic>:6)
	at $line8.$eval$.$print(<synthetic>:5)
	at $line8.$eval.$print(<synthetic>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:670)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1006)
	at scala.tools.nsc.interpreter.IMain.$anonfun$doInterpret$1(IMain.scala:506)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:43)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:505)
	at scala.tools.nsc.interpreter.IMain.$anonfun$doInterpret$3(IMain.scala:519)
	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:519)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:503)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:501)
	at org.jetbrains.jps.incremental.scala.local.worksheet.repl_interface.ILoopWrapper213Impl.processChunk(ILoopWrapper213Impl.scala:62)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactory.$anonfun$loadReplWrapperAndRun$6(ILoopWrapperFactory.scala:84)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactory.$anonfun$loadReplWrapperAndRun$6$adapted(ILoopWrapperFactory.scala:73)
	at scala.collection.ArrayOps$WithFilter.foreach(ArrayOps.scala:73)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactory.loadReplWrapperAndRun(ILoopWrapperFactory.scala:73)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.loadReplWrapperAndRun(ILoopWrapperFactoryHandler.scala:58)
	at org.jetbrains.jps.incremental.scala.local.worksheet.WorksheetServer.loadAndRun(WorksheetServer.scala:31)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:163)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:141)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:131)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:138)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:115)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:71)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)

Fiber:Id(1618398727897,0) was supposed to continue to:
  a future continuation at $line5.$read$$iw$Traitable$.live(<console>:9)
  a future continuation at zio.ZIO.asService(ZIO.scala:200)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged$.fromEffect(ZManaged.scala:1782)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  a future continuation at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2306)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged.map(ZManaged.scala:459)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1043)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1042)
  a future continuation at $line8.$read$$iw.res0(<console>:1)

Fiber:Id(1618398727897,0) execution trace:
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.provideSome(ZIO.scala:1202)
  at zio.ZManaged.flatMap(ZManaged.scala:313)
  at zio.ZManaged$.succeed(ZManaged.scala:2341)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1321)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
  at zio.ZIO.flatten(ZIO.scala:648)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
  at zio.ZIO$.bracketExit(ZIO.scala:2337)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4079)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.Semaphore.releaseN0(Semaphore.scala:116)
  at zio.Semaphore.withPermits(Semaphore.scala:61)
  at zio.ZIO.run(ZIO.scala:1691)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZRefM$UnifiedSyntax$.modify$extension(ZRefM.scala:429)
  at zio.ZRef$Atomic.set(ZRef.scala:221)
  at zio.ZRefM$UnifiedSyntax$.modify(ZRefM.scala:429)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2282)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2282)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2282)
  at zio.Promise$.makeAs(Promise.scala:244)
  at zio.Promise$.make(Promise.scala:238)
  at zio.ZIO$.fiberId(ZIO.scala:2763)
  at zio.ZIO$.descriptor(ZIO.scala:2553)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2281)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2262)
  at zio.ZRef$Atomic.get(ZRef.scala:203)
  at zio.Semaphore.withPermits(Semaphore.scala:61)
  at zio.Semaphore.withPermits(Semaphore.scala:61)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.Semaphore.prepare(Semaphore.scala:84)
  at zio.Promise$.makeAs(Promise.scala:244)
  at zio.Promise$.make(Promise.scala:238)
  at zio.ZIO$.fiberId(ZIO.scala:2763)
  at zio.ZIO$.descriptor(ZIO.scala:2553)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.provideSome(ZIO.scala:1202)
  at zio.ZManaged.foldCauseM(ZManaged.scala:385)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2306)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2303)
  at zio.Promise.completeWith(Promise.scala:114)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2303)
  at zio.ZManaged$ReleaseMap$$anon$1.add(ZManaged.scala:1325)
  at zio.ZManaged$ReleaseMap$$anon$1.addIfOpen(ZManaged.scala:1335)
  at zio.ZIO.flatten(ZIO.scala:648)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2301)
  at zio.ZRef$Atomic.update(ZRef.scala:339)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2296)
  at zio.ZRef$Atomic.set(ZRef.scala:221)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  at zio.ZIO.run(ZIO.scala:1691)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
  at zio.ZIO$.bracketExit(ZIO.scala:2337)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.ZIO.run(ZIO.scala:1691)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.flatMap(ZManaged.scala:314)
  at zio.ZManaged.flatMap(ZManaged.scala:313)
  at zio.ZManaged$.succeed(ZManaged.scala:2341)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1321)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
  at zio.ZIO.flatten(ZIO.scala:648)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
  at zio.ZIO$.bracketExit(ZIO.scala:2337)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4079)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.Semaphore.releaseN0(Semaphore.scala:116)

Fiber:Id(1618398727897,0) was spawned by: <empty trace>
zio.FiberFailure: Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Could not find {$read::$iw::Traitable[=? %1:0 ? Option[+1:0]] & tag::Tagged[=$read::$iw::Marker]} inside Map({$read::$iw::Traitable[=? %1:0 ? Option[+1:0]] & tag::Tagged[=$read::$iw::Marker]} -> $anon$1@6a60851f)
	at zio.Has$HasSyntax$.$anonfun$get$extension$2(Has.scala:181)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:228)
	at zio.Has$HasSyntax$.$anonfun$get$extension$1(Has.scala:181)
	at scala.collection.immutable.Map$Map1.getOrElse(Map.scala:250)
	at zio.Has$HasSyntax$.get$extension(Has.scala:179)
	at zio.ZIO$.$anonfun$service$1(ZIO.scala:3848)
	at zio.ZIO$AccessPartiallyApplied$.$anonfun$apply$9(ZIO.scala:4238)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:549)
	at zio.Runtime.unsafeRunWith(Runtime.scala:207)
	at zio.Runtime.unsafeRunSync(Runtime.scala:81)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:78)
	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:273)
	at zio.Runtime.unsafeRun(Runtime.scala:58)
	at zio.Runtime.unsafeRun$(Runtime.scala:57)
	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:273)
	at <init>(<console>:1)
	at <init>(<console>:13)
	at .<clinit>(<console>)
	at .lzycompute(<synthetic>:6)
	at .$print(<synthetic>:5)
	at $print(<synthetic>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:670)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1006)
	at scala.tools.nsc.interpreter.IMain.$anonfun$doInterpret$1(IMain.scala:506)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:43)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:505)
	at scala.tools.nsc.interpreter.IMain.$anonfun$doInterpret$3(IMain.scala:519)
	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:519)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:503)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:501)
	at org.jetbrains.jps.incremental.scala.local.worksheet.repl_interface.ILoopWrapper213Impl.processChunk(ILoopWrapper213Impl.scala:62)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactory.$anonfun$loadReplWrapperAndRun$6(ILoopWrapperFactory.scala:84)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactory.$anonfun$loadReplWrapperAndRun$6$adapted(ILoopWrapperFactory.scala:73)
	at scala.collection.ArrayOps$WithFilter.foreach(ArrayOps.scala:73)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactory.loadReplWrapperAndRun(ILoopWrapperFactory.scala:73)
	at org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.loadReplWrapperAndRun(ILoopWrapperFactoryHandler.scala:58)
	at org.jetbrains.jps.incremental.scala.local.worksheet.WorksheetServer.loadAndRun(WorksheetServer.scala:31)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:163)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:141)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:131)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:138)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:115)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:71)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)

Fiber:Id(1618398727897,0) was supposed to continue to:
  a future continuation at Traitable$.live(<console>:9)
  a future continuation at zio.ZIO.asService(ZIO.scala:200)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged$.fromEffect(ZManaged.scala:1782)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  a future continuation at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2306)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged.map(ZManaged.scala:459)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1043)
  a future continuation at zio.ZIO.run(ZIO.scala:1691)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1042)
  a future continuation at res0(<console>:1)

Fiber:Id(1618398727897,0) execution trace:
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.provideSome(ZIO.scala:1202)
  at zio.ZManaged.flatMap(ZManaged.scala:313)
  at zio.ZManaged$.succeed(ZManaged.scala:2341)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1321)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
  at zio.ZIO.flatten(ZIO.scala:648)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
  at zio.ZIO$.bracketExit(ZIO.scala:2337)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4079)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.Semaphore.releaseN0(Semaphore.scala:116)
  at zio.Semaphore.withPermits(Semaphore.scala:61)
  at zio.ZIO.run(ZIO.scala:1691)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZRefM$UnifiedSyntax$.modify$extension(ZRefM.scala:429)
  at zio.ZRef$Atomic.set(ZRef.scala:221)
  at zio.ZRefM$UnifiedSyntax$.modify(ZRefM.scala:429)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2282)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2282)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2282)
  at zio.Promise$.makeAs(Promise.scala:244)
  at zio.Promise$.make(Promise.scala:238)
  at zio.ZIO$.fiberId(ZIO.scala:2763)
  at zio.ZIO$.descriptor(ZIO.scala:2553)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2281)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2262)
  at zio.ZRef$Atomic.get(ZRef.scala:203)
  at zio.Semaphore.withPermits(Semaphore.scala:61)
  at zio.Semaphore.withPermits(Semaphore.scala:61)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.Semaphore.prepare(Semaphore.scala:84)
  at zio.Promise$.makeAs(Promise.scala:244)
  at zio.Promise$.make(Promise.scala:238)
  at zio.ZIO$.fiberId(ZIO.scala:2763)
  at zio.ZIO$.descriptor(ZIO.scala:2553)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.provideSome(ZIO.scala:1202)
  at zio.ZManaged.foldCauseM(ZManaged.scala:385)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2306)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2303)
  at zio.Promise.completeWith(Promise.scala:114)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2303)
  at zio.ZManaged$ReleaseMap$$anon$1.add(ZManaged.scala:1325)
  at zio.ZManaged$ReleaseMap$$anon$1.addIfOpen(ZManaged.scala:1335)
  at zio.ZIO.flatten(ZIO.scala:648)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2301)
  at zio.ZRef$Atomic.update(ZRef.scala:339)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2296)
  at zio.ZRef$Atomic.set(ZRef.scala:221)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  at zio.ZIO.run(ZIO.scala:1691)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
  at zio.ZIO$.bracketExit(ZIO.scala:2337)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.ZIO.run(ZIO.scala:1691)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.flatMap(ZManaged.scala:314)
  at zio.ZManaged.flatMap(ZManaged.scala:313)
  at zio.ZManaged$.succeed(ZManaged.scala:2341)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1321)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2286)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
  at zio.ZIO.flatten(ZIO.scala:648)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
  at zio.ZIO$.bracketExit(ZIO.scala:2337)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4079)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.Semaphore.releaseN0(Semaphore.scala:116)

Fiber:Id(1618398727897,0) was spawned by: <empty trace>
```

**Comment by AntonShtyrkin** [comment]
@neko-kai Looks like i've got a similar problem with this.

Reproduced on this example https://scastie.scala-lang.org/DGRkP6ioQQqIc5uxgv6xPg:

```
import zio.test.Assertion._
import zio.test._
import zio._
import shapeless.tag
import shapeless.tag.@@

object SendSpec extends DefaultRunnableSpec {

  sealed trait Marker
  sealed trait Marker1 
  
  trait Traitable[F[_]] {
    def get(): Unit
  }

  object Traitable {
    val live =
      (for {
        s  <- ZIO.service[Traitable[Option] @@ Marker]
        s1 <- ZIO.service[Traitable[Option] @@ Marker1]
      } yield s).toLayer
  }

  val t = new Traitable[Option] {
    def get() = println("Oleg")
  }

  val v = (ZLayer.succeed(tag[Marker](t)) ++ ZLayer.succeed(tag[Marker1](t)))  >>> Traitable.live

  override def spec: ZSpec[Environment, Failure] =
    suite("Spec")(
      testM("error") {
        for {
          _ <- v.build.use(p => ZIO.succeed(p.get[Traitable[Option] @@ Marker].get()))
        } yield assert(true)(equalTo(true))
      }
    )
}
```

scala 2.13.5 + shapeless 2.3.3 + zio 1.0.6

```
Fiber failed.
    An unchecked error was produced.
    java.lang.Error: Defect in zio.Has: Set({SendSpec::Traitable[=λ %2:0 → Option[+2:0]] & tag::Tagged[=SendSpec::Marker1]}) statically known to be contained within the environment are missing
    	at zio.Has$HasSyntax$.prune$extension(Has.scala:198)
    	at zio.Has$HasSyntax$.union$extension(Has.scala:210)
    	at zio.Has$Union$$anon$2.union(Has.scala:92)
    	at zio.Has$Union$$anon$2.union(Has.scala:90)
    	at zio.ZLayer.$anonfun$$plus$plus$1(ZLayer.scala:54)
    	at zio.ZManaged.$anonfun$zipWithPar$6(ZManaged.scala:1156)
    	at zio.ZIO.$anonfun$zipWithPar$7(ZIO.scala:2227)
    	at zio.ZIO.$anonfun$zipWithPar$2(ZIO.scala:2217)
    	at zio.ZIO$MapFn.apply(ZIO.scala:4284)
    	at zio.ZIO$MapFn.apply(ZIO.scala:4282)
    	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:914)
    	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    
    Fiber:Id(1618401012678,60) was supposed to continue to:
      a future continuation at zio.ZManaged.mapM(ZManaged.scala:484)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
      a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2289)
      a future continuation at zio.ZLayer$MemoMap$$anon$1.getOrElseMemoize(ZLayer.scala:2306)
      a future continuation at zio.ZManaged.foldCauseM(ZManaged.scala:385)
      a future continuation at zio.ZManaged.map(ZManaged.scala:459)
      a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
      a future continuation at zio.ZManaged.flatMap(ZManaged.scala:314)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
      a future continuation at zio.ZManaged.use(ZManaged.scala:1043)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZManaged.use(ZManaged.scala:1042)
      a future continuation at SendSpec$$anonfun$spec$1$$anonfun$apply$4.apply(main.scala:34)
      a future continuation at zio.test.package$ZTest$.apply(package.scala:110)
    
    Fiber:Id(1618401012678,60) execution trace:
      at zio.ZIO.zipWithPar(ZIO.scala:2217)
      at zio.ZIO$ZipLeftFn.apply(ZIO.scala:4267)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2950)
      at zio.ZIO$.foreach_(ZIO.scala:2946)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.Fiber.join(Fiber.scala:173)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.Fiber.join(Fiber.scala:173)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZIO.onInterrupt(ZIO.scala:1012)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZIO$._IdentityFn(ZIO.scala:4079)
      at zio.internal.FiberContext.await(FiberContext.scala:785)
      at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2646)
      at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2646)
      at zio.ZIO.zipWithPar(ZIO.scala:2217)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2950)
      at zio.ZIO$.foreach_(ZIO.scala:2946)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.internal.FiberContext.raceWithImpl(FiberContext.scala:230)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2948)
      at zio.ZIO$.foreach_(ZIO.scala:2950)
      at zio.ZIO$.foreach_(ZIO.scala:2946)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.internal.FiberContext.raceWithImpl(FiberContext.scala:227)
      at zio.ZIO.zipWithPar(ZIO.scala:2231)
      at zio.ZManaged.zipWithPar(ZManaged.scala:1148)
      at zio.ZIO.$amp$amp$amp(ZIO.scala:59)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.ZIO$.bracketExit(ZIO.scala:2337)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.ZIO.run(ZIO.scala:1691)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZManaged$.makeExit(ZManaged.scala:1982)
      at zio.ZManaged$ReleaseMap$$anon$1.add(ZManaged.scala:1325)
      at zio.ZManaged$ReleaseMap$$anon$1.addIfOpen(ZManaged.scala:1335)
      at zio.ZIO.flatten(ZIO.scala:648)
      at zio.ZRef$Atomic.modify(ZRef.scala:215)
      at zio.ZManaged$.makeExit(ZManaged.scala:1981)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.ZIO$.bracketExit(ZIO.scala:2337)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.ZIO.run(ZIO.scala:1691)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1321)
      at zio.ZRef$.make(ZRef.scala:756)
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
      at zio.ZManaged$.makeExit(ZManaged.scala:1980)
      at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4238)
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
      at zio.ZIO.provideSome(ZIO.scala:1202)
      at zio.ZIO.zipWith(ZIO.scala:2201)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
      at zio.ZIO$.bracketExit(ZIO.scala:2337)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.ZIO.run(ZIO.scala:1691)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZManaged$.makeExit(ZManaged.scala:1982)
      at zio.ZManaged$ReleaseMap$$anon$1.add(ZManaged.scala:1325)
      at zio.ZManaged$ReleaseMap$$anon$1.addIfOpen(ZManaged.scala:1335)
      at zio.ZIO.flatten(ZIO.scala:648)
      at zio.ZRef$Atomic.modify(ZRef.scala:215)
      at zio.ZManaged$.makeExit(ZManaged.scala:1981)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
      at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2712)
    
    Fiber:Id(1618401012678,60) was spawned by:
    
    Fiber:Id(1618401012349,32) was supposed to continue to:
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:373)
      a future continuation at zio.test.package$Annotations$$anon$1.withAnnotation(package.scala:639)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO$BracketRelease_.apply(ZIO.scala:4210)
      a future continuation at zio.FiberRef.locally(FiberRef.scala:96)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
    
    Fiber:Id(1618401012349,32) execution trace:
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:614)
      at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:374)
      at zio.Supervisor$.fibersIn(Supervisor.scala:170)
      at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:374)
      at zio.ZIO$TapFn.apply(ZIO.scala:4279)
      at zio.test.package$Annotations$.annotate(package.scala:612)
      at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:364)
      at zio.ZRef$.make(ZRef.scala:756)
      at zio.ZIO$BracketRelease_.apply(ZIO.scala:4210)
    
    Fiber:Id(1618401012349,32) was spawned by:
    
    Fiber:Id(1618401010610,0) was supposed to continue to:
      a future continuation at zio.ZIO$.foreach(ZIO.scala:2886)
      a future continuation at zio.ZIO$.foreach(ZIO.scala:2887)
      a future continuation at zio.ZIO$.foreachPar_(ZIO.scala:3083)
      a future continuation at zio.ZIO$.foreachPar_(ZIO.scala:3083)
      a future continuation at zio.ZIO$.foreachParN(ZIO.scala:3123)
      a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:1445)
      a future continuation at zio.ZManaged$.foreachParN(ZManaged.scala:1720)
      a future continuation at zio.ZManaged.mapM(ZManaged.scala:484)
      a future continuation at zio.ZIO.run(ZIO.scala:1691)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
    
    Fiber:Id(1618401010610,0) execution trace:
      at zio.ZIO.zipWith(ZIO.scala:2201)
      at zio.ZIO$.foreach(ZIO.scala:2886)
      at zio.ZIO.zipWith(ZIO.scala:2201)
      at zio.ZIO$.foreach(ZIO.scala:2886)
      at zio.ZIO.zipWith(ZIO.scala:2201)
      at zio.ZIO$.foreach(ZIO.scala:2886)
      at zio.ZIO.zipWith(ZIO.scala:2201)
      at zio.ZIO$.foreach(ZIO.scala:2885)
      at zio.ZIO$.foreachPar_(ZIO.scala:3048)
      at zio.ZIO$.foreachPar_(ZIO.scala:3048)
    
    Fiber:Id(1618401010610,0) was spawned by: <empty trace>
```

**Comment by AntonShtyrkin** [comment]
zio 1.0.1 - works fine

**Comment by Lando-L** [comment]
The bug also appears every time a type parameter is introduced (`zio 1.0.6` with `scala 3.0.0-RC2`).

```
trait Service[T]:
  def foo(t: T): UIO[T]

object Service:
  val live: ULayer[Has[Service[Int]]] =
    ZLayer.succeed {
      new Service[Int]:
        def foo(t: Int) =
          ZIO.succeed(t)
    }

def foo[T: Tag](t: T): URIO[Has[Service[T]], T] =
  ZIO.serviceWith(_.foo(t))
```

**Comment by artkostm** [comment]
Using the +!+ operator instead of ++ can help (zio 1.0.7, sttp 3.3.0)

**Comment by adamgfraser** [comment]
@artkostm I wonder if we should use that more broadly.

**Comment by lxwbr** [comment]
Using `1.0.8` with `scala 3.0.0` and having the same error when using type parameters as described here: https://github.com/zio/zio/issues/4809#issuecomment-822001203

**Comment by neko-kai** [comment]
@lxwbr @Lando-L 
This is a different error - type parameter tags are not supported at all on 3 yet https://github.com/zio/izumi-reflect/issues/103

Workaround: write
```
def foo[T](t: T)(given Tag[Service[T]]): URIO[Has[Service[T]], T] =
  ZIO.serviceWith(_.foo(t))
```

Instead of `T: Tag`

**Comment by lxwbr** [comment]
@neko-kai thanks, but I can't get this to compile, it yields following error:
```
[error] -- [E040] Syntax Error: package.scala:14:17 
[error] 14 |def foo[T](t: T)(given Tag[Service[T]]): URIO[Has[Service[T]], T] =
[error]    |                 ^^^^^
[error]    |                 an identifier expected, but 'given' found
```

**Comment by neko-kai** [comment]
@lxwbr `using Tag[Service[T]]` my bad

**Comment by lxwbr** [comment]
Thanks a lot @neko-kai, that solved it for me

**Comment by marcsaegesser** [comment]
Any update on this? I ran into the `statically known to be contained within the environment are missing` problem when I added a new module to my application. I originally thought my new module was bad, but I found that adding _any_ module to my environment , even just Console.live`, caused the error. And then removing _any_ module from the environment caused the problem to go away.

I was able to work around the problem for now by using `+!+` rather that `++` (i.e. unionAll rather than union). UnionAll seems to not call the `prune` method which is where the problem occurs. To make this work I had to add the appropriate ZIO layers (e.g. `Clock.live`) and then use `provideLayer` rather than `provideCustomLayer`.

I'm using ZIO 1.0.9 and Scala 3.0.0.

**Comment by evazamtz** [comment]
> Any update on this? I ran into the `statically known to be contained within the environment are missing` problem when I added a new module to my application. I originally thought my new module was bad, but I found that adding _any_ module to my environment , even just Console.live`, caused the error. And then removing _any_ module from the environment caused the problem to go away.
> 
> I was able to work around the problem for now by using `+!+` rather that `++` (i.e. unionAll rather than union). UnionAll seems to not call the `prune` method which is where the problem occurs. To make this work I had to add the appropriate ZIO layers (e.g. `Clock.live`) and then use `provideLayer` rather than `provideCustomLayer`.
> 
> I'm using ZIO 1.0.9 and Scala 3.0.0.

Thanks for the workaround tip. Got the same problem on ZIO 1.0.9 and scala 3.0.0 after adding the 5th layer.

**Comment by pshirshov** [comment]
@kitlangton is working on a fix for this here: https://github.com/zio/izumi-reflect/pull/239

Though that's not a bug. This is a missing feature :D

**Comment by virusdave** [comment]
Can we get a bumped zio 1.x release with izumi dependencies update to include the update from https://github.com/zio/izumi-reflect/pull/239 ?  It looks from izumi release notes as if libraries and user code both need to be updated to work successfully.

**Comment by adamgfraser** [comment]
Yes will do shortly.

**Comment by adamgfraser** [comment]
Actually I think we can't update to `izumi-reflect` 2.0 because it is not binary compatible with 1.0 so it would cause ZIO itself to break binary compatibility. So we would have to look to back port improvements to `izumi-refect` 2.0 to 1.0.

@neko-kai or @pshirshov Can you confirm that is correct?

**Comment by neko-kai** [comment]
@adamgfraser 
It is _binary_ compatible, the breakage is in:

* Fixed a bug when types parameterized by a wildcard would lose their prefix (zio/izumi-reflect#203)

It concerns only types with wildcard parameters, e.g. `Set[_]` (old Tag[Set[_]] will not be equal to new Tag[Set[_]] because the prefix `scala.collection.immutable` is now correctly included in the presence of a wildcard parameter)

>  back port improvements to izumi-refect 2.0 to 1.0.

That would be very costly, it's easier to add a workaround to ignore the prefix in comparison when wildcards are present in older tags. e.g. Kit could do that by bumping the binary format version and applying the heuristic when comparing new and old tags. The reason I didn't add a compatibility workaround for that is that I assumed there aren't many services parameterized with wildcards in zio-* libraries that will be broken by this - and non-library users aren't affected anyway.

**Comment by neko-kai** [comment]
@virusdave You can update izumi-reflect in just your project by including it in dependencies, libraries don't have to be recompiled unless the composition of polymorphic tags (or specifically a lack of it in old Scala 3 versions) happens inside the library. (Also we might be talking about different fixes if you're not using Scala 3, only Scala 3 errors were addressed by that PR)

**Comment by virusdave** [comment]
> @virusdave You can update izumi-reflect in just your project by including it in dependencies, libraries don't have to be recompiled unless the composition of polymorphic tags (or specifically a lack of it in old Scala 3 versions) happens inside the library. (Also we might be talking about different fixes if you're not using Scala 3, only Scala 3 errors were addressed by that PR)

Yup, thanks.  This is actually what i did immediately after responding, and it does work (in that there's not a binary breakage), however it did not solve the underlying problem of `Has` throwing a runtime exception, so I ended up redesigning the system in question to avoid the issue :(  I'll file a separate followup ticket for a feature enhancement to support it.

**Comment by pshirshov** [comment]
This may be somehow relevant: https://github.com/zio/izumi-reflect/issues/31
