### ISSUE TITLE
zio-test: Comparing Chunk to Seq causes ClassCastException

### ISSUE THREAD

**Issue by andrzejressel** [zio/zio#8754]
Scala 3 (2.13 does not compile with `found Seq, require Chunk` error)
Both 2.0 and 2.1-RC

https://scastie.scala-lang.org/7CX9Y9D3QYq0v4TNcsIDmw

```scala
object Suite extends ZIOSpecDefault {
  override def spec = suite("suite") {
    test("test") {
     assertTrue(Chunk(1, 2, 3) == Seq(1, 2, 3, 4));
    }
  }
}
```

```
  - suite[2m / test
    ✗ ERROR: java.lang.ClassCastException: class scala.collection.immutable.$colon$colon cannot be cast to class zio.Chunk (scala.collection.immutable.$colon$colon is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @5ad07354; zio.Chunk is in unnamed module of loader sbt.internal.ReverseLookupClassLoader @3094bb)
      zio.test.diff.DiffInstances.mkSeqDiff$$anonfun$1(Diff.scala:113)
      zio.test.internal.SmartAssertions$.equalTo$$anonfun$1(SmartAssertions.scala:291)
    Chunk(1, 2, 3) == Seq(1, 2, 3, 4)
    [2m(1, 2, 3) = Chunk(1, 2, 3)
    [2mChunk = zio.Chunk$@3f018ce
    at /tmp/scastie5353637521019907974/src/main/scala/main.scala:10 
```

**Comment by andrzejressel** [comment]
I believe it's caused by
```scala
      case Unseal(MethodCall(lhs, "==", tpes, Some(List(rhs)))) =>
        val span = getSpan(rhs)
        lhs.tpe.widen.asType match {
          case '[l] =>
            Expr.summon[OptionalImplicit[Diff[l]]] match {
              case Some(optDiff) =>
                '{${transform(lhs.asExpr)} >>> SmartAssertions.equalTo(${rhs.asExpr})($optDiff.asInstanceOf[OptionalImplicit[Diff[Any]]]).span($span)}.asExprOf[TestArrow[Any, A]]
              case _ => throw new Error("OptionalImplicit should be always available")
            }
        }
```

lhs should be first common class (GCD of class I guess)

**Comment by andrzejressel** [comment]
I was wrong with my initial checks - Chunk and Seq are related. It just required proper mapping logic like in Scala 2.13

**Comment by joroKr21** [comment]
> lhs should be first common class (GCD of class I guess)

LUB and GLB are not exposed in Scala 3 macros. You could make `Diff[-A]` contravariant and use `A | B`.

**Comment by andrzejressel** [comment]
I was writing that before i knew how Scala 2 macro work - it should propably work like it. So one class has to be subtype of another.

**Comment by joroKr21** [comment]
> I was writing that before i knew how Scala 2 macro work - it should propably work like it.

Not sure what you mean. This is Scala 3.

> So one class has to be subtype of another.

Nope, LUB doesn't require one class to be subtype of the other.

**Comment by andrzejressel** [comment]
I meant that `assertTrue` in Scala 2 does not allow unrelated classes for any comparison. Scala 3 should propably have the same behaviour.

**Comment by andrzejressel** [comment]
S3 unfortunately does allow it and it generate pretty ugly comparisons - I think I would prefer for it to be reported during compilation.

**Comment by joroKr21** [comment]
They are related though, `Chunk` extends `Seq`

**Comment by andrzejressel** [comment]
Yes, this specific issue is about directly related classes (which I didn't know at the beginning) and I want to focus on that.

The issue with non directly related classes is that they are all ultimately related anyway thought Any (which have diff instance). And I like Scala 2 behavior of not allowing comparisons of non directly related classes.

**Comment by andrzejressel** [comment]
Maybe it just my thing - but when I'm comparing A to option A or Seq A, I'd rather have compile error than downcast to Any.

**Comment by guizmaii** [comment]
@kyri-petrou Isn't this fixed by #8874?

**Comment by andrzejressel** [comment]
Nope, the other is similar but it's for Scala 2.13. This one is for Scala 3.

**Comment by hearnadam** [comment]
```
import zio.test.*
import zio.Chunk

assertTrue(Chunk(1, 2, 3) == Seq(1, 2, 3, 4)).result.result
```

Still an issue: https://scastie.scala-lang.org/kZOjYqcpSg6Ey00vzwpwDg
